<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('players')->truncate();
        DB::table('teams')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $now = now();

        $teams = [
            // LA LIGA
            ['id' => 'bar', 'name' => 'Barcelona', 'shortName' => 'BAR', 'strength' => 99, 'primaryColor' => '#a50044', 'secondaryColor' => '#004d98', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8634.png', 'tier' => 1],
            ['id' => 'rma', 'name' => 'Real Madrid', 'shortName' => 'RMA', 'strength' => 92, 'primaryColor' => '#ffffff', 'secondaryColor' => '#1e3a8a', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8633.png', 'tier' => 1],
            ['id' => 'atm', 'name' => 'Atlético Madrid', 'shortName' => 'ATM', 'strength' => 88, 'primaryColor' => '#cb3524', 'secondaryColor' => '#171796', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9906.png', 'tier' => 1],
            ['id' => 'gir', 'name' => 'Girona', 'shortName' => 'GIR', 'strength' => 84, 'primaryColor' => '#ef3340', 'secondaryColor' => '#ffffff', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/7732.png', 'tier' => 1],
            ['id' => 'ath', 'name' => 'Athletic Club', 'shortName' => 'ATH', 'strength' => 83, 'primaryColor' => '#e30613', 'secondaryColor' => '#000000', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8315.png', 'tier' => 1],
            ['id' => 'rso', 'name' => 'Real Sociedad', 'shortName' => 'RSO', 'strength' => 82, 'primaryColor' => '#0066b2', 'secondaryColor' => '#ffffff', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8560.png', 'tier' => 1],
            ['id' => 'bet', 'name' => 'Real Betis', 'shortName' => 'BET', 'strength' => 80, 'primaryColor' => '#0bb363', 'secondaryColor' => '#ffffff', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8603.png', 'tier' => 1],
            ['id' => 'vil', 'name' => 'Villarreal', 'shortName' => 'VIL', 'strength' => 79, 'primaryColor' => '#fbe10f', 'secondaryColor' => '#00519e', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10205.png', 'tier' => 1],
            ['id' => 'val', 'name' => 'Valencia', 'shortName' => 'VAL', 'strength' => 77, 'primaryColor' => '#ffffff', 'secondaryColor' => '#000000', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10267.png', 'tier' => 1],
            ['id' => 'osa', 'name' => 'Osasuna', 'shortName' => 'OSA', 'strength' => 76, 'primaryColor' => '#da291c', 'secondaryColor' => '#0a1d56', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8371.png', 'tier' => 1],
            ['id' => 'get', 'name' => 'Getafe', 'shortName' => 'GET', 'strength' => 75, 'primaryColor' => '#005999', 'secondaryColor' => '#ffffff', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8305.png', 'tier' => 1],
            ['id' => 'cel', 'name' => 'Celta Vigo', 'shortName' => 'CEL', 'strength' => 75, 'primaryColor' => '#8ac3ee', 'secondaryColor' => '#ce0e2d', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9910.png', 'tier' => 1],
            ['id' => 'sev', 'name' => 'Sevilla', 'shortName' => 'SEV', 'strength' => 76, 'primaryColor' => '#ffffff', 'secondaryColor' => '#d4001f', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8302.png', 'tier' => 1],
            ['id' => 'mal', 'name' => 'Mallorca', 'shortName' => 'MAL', 'strength' => 74, 'primaryColor' => '#e20613', 'secondaryColor' => '#000000', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8661.png', 'tier' => 1],
            ['id' => 'ray', 'name' => 'Rayo Vallecano', 'shortName' => 'RAY', 'strength' => 73, 'primaryColor' => '#ffffff', 'secondaryColor' => '#ce0e2d', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8370.png', 'tier' => 1],
            ['id' => 'ala', 'name' => 'Alavés', 'shortName' => 'ALA', 'strength' => 72, 'primaryColor' => '#0057a6', 'secondaryColor' => '#ffffff', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9866.png', 'tier' => 1],
            ['id' => 'pal', 'name' => 'Las Palmas', 'shortName' => 'PAL', 'strength' => 71, 'primaryColor' => '#ffc400', 'secondaryColor' => '#00539f', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8306.png', 'tier' => 1],
            ['id' => 'leg', 'name' => 'Leganés', 'shortName' => 'LEG', 'strength' => 70, 'primaryColor' => '#0055a4', 'secondaryColor' => '#ffffff', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/7854.png', 'tier' => 1],
            ['id' => 'val2', 'name' => 'Valladolid', 'shortName' => 'VLD', 'strength' => 69, 'primaryColor' => '#5c2d7f', 'secondaryColor' => '#ffffff', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10281.png', 'tier' => 1],
            ['id' => 'esp', 'name' => 'Espanyol', 'shortName' => 'ESP', 'strength' => 70, 'primaryColor' => '#338ecc', 'secondaryColor' => '#ffffff', 'isUCL' => false, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8558.png', 'tier' => 1],

            // EUROPEAN GIANTS
            ['id' => 'mci', 'name' => 'Manchester City', 'shortName' => 'MCI', 'strength' => 96, 'primaryColor' => '#6CABDD', 'secondaryColor' => '#1C2C5B', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8456.png', 'tier' => 2],
            ['id' => 'liv', 'name' => 'Liverpool', 'shortName' => 'LIV', 'strength' => 96, 'primaryColor' => '#C8102E', 'secondaryColor' => '#00B2A9', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8650.png', 'tier' => 2],
            ['id' => 'ars', 'name' => 'Arsenal', 'shortName' => 'ARS', 'strength' => 94, 'primaryColor' => '#EF0107', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9825.png', 'tier' => 2],
            ['id' => 'avl', 'name' => 'Aston Villa', 'shortName' => 'AVL', 'strength' => 85, 'primaryColor' => '#95BBE5', 'secondaryColor' => '#670E36', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10252.png', 'tier' => 2],
            ['id' => 'bay', 'name' => 'Bayern Munich', 'shortName' => 'BAY', 'strength' => 96, 'primaryColor' => '#DC052D', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9823.png', 'tier' => 2],
            ['id' => 'dor', 'name' => 'Dortmund', 'shortName' => 'BVB', 'strength' => 89, 'primaryColor' => '#FDE100', 'secondaryColor' => '#000000', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9789.png', 'tier' => 2],
            ['id' => 'rbl', 'name' => 'Leipzig', 'shortName' => 'RBL', 'strength' => 86, 'primaryColor' => '#DD0741', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/178475.png', 'tier' => 2],
            ['id' => 'lev', 'name' => 'Leverkusen', 'shortName' => 'B04', 'strength' => 92, 'primaryColor' => '#E32221', 'secondaryColor' => '#000000', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8178.png', 'tier' => 2],
            ['id' => 'stu', 'name' => 'Stuttgart', 'shortName' => 'VFB', 'strength' => 82, 'primaryColor' => '#FFFFFF', 'secondaryColor' => '#E32221', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10269.png', 'tier' => 2],
            ['id' => 'int', 'name' => 'Inter', 'shortName' => 'INT', 'strength' => 92, 'primaryColor' => '#010E80', 'secondaryColor' => '#000000', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8636.png', 'tier' => 2],
            ['id' => 'mil', 'name' => 'Milan', 'shortName' => 'MIL', 'strength' => 88, 'primaryColor' => '#FB090B', 'secondaryColor' => '#000000', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8564.png', 'tier' => 2],
            ['id' => 'juv', 'name' => 'Juventus', 'shortName' => 'JUV', 'strength' => 87, 'primaryColor' => '#000000', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9885.png', 'tier' => 2],
            ['id' => 'ata', 'name' => 'Atalanta', 'shortName' => 'ATA', 'strength' => 85, 'primaryColor' => '#1E71B8', 'secondaryColor' => '#000000', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8524.png', 'tier' => 2],
            ['id' => 'bol', 'name' => 'Bologna', 'shortName' => 'BOL', 'strength' => 80, 'primaryColor' => '#1A2F48', 'secondaryColor' => '#A21C26', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9857.png', 'tier' => 2],
            ['id' => 'psg', 'name' => 'Paris SG', 'shortName' => 'PSG', 'strength' => 94, 'primaryColor' => '#004170', 'secondaryColor' => '#DA291C', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9847.png', 'tier' => 2],
            ['id' => 'mon', 'name' => 'Monaco', 'shortName' => 'MON', 'strength' => 83, 'primaryColor' => '#E51D1F', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9829.png', 'tier' => 2],
            ['id' => 'bre', 'name' => 'Brest', 'shortName' => 'SB29', 'strength' => 78, 'primaryColor' => '#DD0000', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8521.png', 'tier' => 2],
            ['id' => 'lil', 'name' => 'Lille', 'shortName' => 'LOSC', 'strength' => 82, 'primaryColor' => '#E01E13', 'secondaryColor' => '#20325F', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8639.png', 'tier' => 2],
            ['id' => 'psv', 'name' => 'PSV', 'shortName' => 'PSV', 'strength' => 81, 'primaryColor' => '#FF0000', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8640.png', 'tier' => 2],
            ['id' => 'fey', 'name' => 'Feyenoord', 'shortName' => 'FEY', 'strength' => 80, 'primaryColor' => '#FF0000', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10235.png', 'tier' => 2],
            ['id' => 'spo', 'name' => 'Sporting', 'shortName' => 'SCP', 'strength' => 84, 'primaryColor' => '#008000', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9768.png', 'tier' => 2],
            ['id' => 'ben', 'name' => 'Benfica', 'shortName' => 'SLB', 'strength' => 83, 'primaryColor' => '#E30613', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9772.png', 'tier' => 2],
            ['id' => 'bru', 'name' => 'Brugge', 'shortName' => 'CLB', 'strength' => 78, 'primaryColor' => '#000000', 'secondaryColor' => '#0067CE', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8342.png', 'tier' => 2],
            ['id' => 'cel_sco', 'name' => 'Celtic', 'shortName' => 'CEL', 'strength' => 77, 'primaryColor' => '#018749', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9925.png', 'tier' => 2],
            ['id' => 'sha', 'name' => 'Shakhtar', 'shortName' => 'SHK', 'strength' => 78, 'primaryColor' => '#F58220', 'secondaryColor' => '#000000', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/9728.png', 'tier' => 2],
            ['id' => 'sal', 'name' => 'Salzburg', 'shortName' => 'RBS', 'strength' => 76, 'primaryColor' => '#D11241', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10013.png', 'tier' => 2],
            ['id' => 'you', 'name' => 'Young Boys', 'shortName' => 'YB', 'strength' => 74, 'primaryColor' => '#FFD700', 'secondaryColor' => '#000000', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10192.png', 'tier' => 2],
            ['id' => 'zag', 'name' => 'Dinamo Zagreb', 'shortName' => 'DIN', 'strength' => 74, 'primaryColor' => '#00539F', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10156.png', 'tier' => 2],
            ['id' => 'crv', 'name' => 'Red Star', 'shortName' => 'RSB', 'strength' => 73, 'primaryColor' => '#E30613', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8687.png', 'tier' => 2],
            ['id' => 'spa', 'name' => 'Sparta Prague', 'shortName' => 'SPA', 'strength' => 75, 'primaryColor' => '#A41034', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10247.png', 'tier' => 2],
            ['id' => 'fer', 'name' => 'Ferencváros', 'shortName' => 'FTC', 'strength' => 72, 'primaryColor' => '#1A8C43', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/8222.png', 'tier' => 2],
            ['id' => 'stg', 'name' => 'Sturm Graz', 'shortName' => 'STU', 'strength' => 72, 'primaryColor' => '#000000', 'secondaryColor' => '#FFFFFF', 'isUCL' => true, 'logoUrl' => 'https://images.fotmob.com/image_resources/logo/teamlogo/10014.png', 'tier' => 2],
        ];

        // 100% Accurate Real-World Rosters & Static Ratings
        // Order exactly matches 4-3-3: GK, RB, CB, CB, LB, CDM, CM, CM, RW, LW, ST (First 11 Start)
        $realPlayers = [
            'bar' => ['Ter Stegen:GK:89', 'Koundé:RB:86', 'Araújo:CB:88', 'Cubarsí:CB:84', 'Balde:LB:85', 'De Jong:CDM:88', 'Pedri:CM:99', 'Gavi:CM:87', 'Yamal:RW:99', 'Raphinha:LW:90', 'Lewandowski:ST:91', 'Peña:GK:78', 'Fort:RB:76', 'Christensen:CB:84', 'Martin:LB:75', 'Casadó:CDM:83', 'Fermín:CM:84', 'Olmo:CAM:87', 'Ferran:RW:81', 'Fati:LW:79', 'Víctor:ST:76', 'Roque:ST:78'],
            'rma' => ['Courtois:GK:90', 'Carvajal:RB:87', 'Rüdiger:CB:88', 'Militao:CB:86', 'Mendy:LB:84', 'Tchouaméni:CDM:85', 'Valverde:CM:89', 'Bellingham:CM:91', 'Rodrygo:RW:86', 'Vinícius Jr:LW:92', 'Mbappé:ST:93', 'Lunin:GK:82', 'Vazquez:RB:80', 'Alaba:CB:83', 'Garcia:LB:79', 'Camavinga:CDM:84', 'Modric:CM:85', 'Brahim:CAM:83', 'Güler:RW:81', 'Ceballos:LW:80', 'Endrick:ST:78', 'Vallejo:CB:75'],
            'atm' => ['Oblak:GK:88', 'Llorente:RB:84', 'Giménez:CB:85', 'Le Normand:CB:84', 'Lino:LB:82', 'Koke:CDM:84', 'De Paul:CM:85', 'Gallagher:CM:83', 'Griezmann:RW:88', 'Alvarez:LW:86', 'Sorloth:ST:83', 'Musso:GK:80', 'Molina:RB:81', 'Witsel:CB:82', 'Mandava:LB:80', 'Barrios:CDM:80', 'Lemar:CM:81', 'Riquelme:CAM:81', 'Correa:RW:82', 'Simeone:LW:78', 'Lenglet:CB:79', 'Azpilicueta:CB:81'],
            'gir' => ['Gazzaniga:GK:82', 'Martinez:RB:80', 'López:CB:81', 'Blind:CB:80', 'Gutiérrez:LB:83', 'Romeu:CDM:79', 'Herrera:CM:80', 'Martín:CM:80', 'Tsygankov:RW:82', 'Gil:LW:80', 'Ruiz:ST:79', 'Lopez:GK:75', 'Francés:RB:76', 'Juanpe:CB:76', 'Danzuma:LB:78', 'Solís:CDM:75', 'Misehouy:CM:74', 'Portu:CAM:79', 'Asprilla:RW:77', 'Danjuma:LW:79', 'Miovski:ST:76', 'Stuani:ST:78'],
            'ath' => ['Simón:GK:85', 'De Marcos:RB:80', 'Vivian:CB:83', 'Paredes:CB:80', 'Yuri:LB:80', 'Vesga:CDM:79', 'Prados:CM:78', 'Sancet:CM:82', 'I. Williams:RW:84', 'N. Williams:LW:86', 'Guruzeta:ST:81', 'Agirrezabala:GK:78', 'Lekue:RB:77', 'Yeray:CB:80', 'Boik:LB:75', 'Ruiz:CDM:78', 'Herrera:CM:79', 'Gómez:CAM:77', 'Berenguer:RW:80', 'Djalo:LW:78', 'Martón:ST:75', 'Serrano:ST:74'],
            'rso' => ['Remiro:GK:84', 'Traoré:RB:81', 'Zubeldia:CB:82', 'Aguerd:CB:81', 'Muñoz:LB:80', 'Zubimendi:CDM:85', 'Turrientes:CM:79', 'Méndez:CM:83', 'Kubo:RW:84', 'Barrenetxea:LW:80', 'Oyarzabal:ST:83', 'Marrero:GK:75', 'Aramburu:RB:76, Elustondo:CB:80', 'Gómez:LB:78', 'Olasagasti:CDM:76', 'Marín:CM:75', 'Zakharyan:CAM:79', 'Becker:RW:78', 'Gómez:LW:77', 'Sadiq:ST:78', 'Óskarsson:ST:77'],
            'bet' => ['Silva:GK:82', 'Bellerín:RB:80', 'Llorente:CB:81', 'Natan:CB:80', 'Perraud:LB:79', 'Cardoso:CDM:80', 'Altimira:CM:77', 'Lo Celso:CM:83', 'Fornals:RW:81', 'Abde:LW:80', 'Roque:ST:80', 'Adrian:GK:76', 'Sabaly:RB:78', 'Bartra:CB:79', 'Rodriguez:LB:76', 'Roca:CDM:80', 'Carvalho:CM:80', 'Isco:CAM:82', 'Ruibal:RW:78', 'Juanmi:LW:78', 'Bakambu:ST:79', 'Avila:ST:79'],
            'vil' => ['Conde:GK:80', 'Femenía:RB:79', 'Albiol:CB:81', 'Costa:CB:80', 'Cardona:LB:78', 'Comesaña:CDM:80', 'Parejo:CM:82', 'Baena:CM:84', 'Pino:RW:82', 'Pérez:LW:81', 'Barry:ST:80', 'Álvarez:GK:75', 'Foyth:RB:81', 'Bailly:CB:80', 'Pedraza:LB:80', 'Terrats:CDM:77', 'Gueye:CM:80', 'Suárez:CAM:79', 'Akhomach:RW:78', 'Bernat:LW:77', 'Pépé:ST:80', 'Cabanes:ST:74'],
            'val' => ['Mamardashvili:GK:85', 'Correia:RB:79', 'Mosquera:CB:81', 'Tárrega:CB:78', 'Gayà:LB:83', 'Pepelu:CDM:81', 'Guerra:CM:80', 'Almeida:CM:79', 'López:RW:79', 'Rioja:LW:80', 'Duro:ST:80', 'Dimitrievski:GK:78', 'Foulquier:RB:77', 'Gasiorowski:CB:76', 'Vázquez:LB:77', 'Guillamón:CDM:78', 'Pérez:CM:75', 'Tejón:CAM:74', 'Canós:RW:77', 'Vallejo:LW:76', 'Gómez:ST:78', 'Mir:ST:78'],
            'osa' => ['Herrera:GK:80', 'Areso:RB:79', 'Catena:CB:80', 'Boyomo:CB:78', 'Bretones:LB:78', 'Torró:CDM:80', 'Moncayola:CM:80', 'Oroz:CM:81', 'Rubén:RW:79', 'Zaragoza:LW:80', 'Budimir:ST:82', 'Fernández:GK:76', 'Vidal:RB:78', 'Cruz:CB:78', 'Peña:LB:77', 'Muñoz:CDM:78', 'Ibáñez:CM:77', 'Gómez:CAM:79', 'Peña:RW:78', 'Arnaiz:LW:77', 'García:ST:79', 'Raúl:ST:78'],
            'get' => ['Soria:GK:82', 'Iglesias:RB:78', 'Djené:CB:80', 'Alderete:CB:79', 'Rico:LB:78', 'Arambarri:CDM:80', 'Milla:CM:80', 'Uche:CM:77', 'Sola:RW:77', 'Pérez:LW:78', 'Mayoral:ST:81', 'Letacek:GK:74', 'Nyom:RB:75', 'Domingos:CB:78', 'Angileri:LB:76', 'Aberdin:CDM:74', 'Santiago:CM:75', 'Aleñá:CAM:79', 'Peter:RW:76', 'Rodríguez:LW:75', 'Yildirim:ST:76', 'Risco:ST:73'],
            'cel' => ['Guaita:GK:80', 'Mingueza:RB:80', 'Starfelt:CB:79', 'Domínguez:CB:77', 'Alonso:LB:78', 'Beltrán:CDM:80', 'Sotelo:CM:77', 'Moriba:CM:78', 'Bamba:RW:80', 'Swedberg:LW:78', 'Aspas:ST:82', 'Villar:GK:75', 'Rodríguez:RB:76', 'Aidoo:CB:78', 'Ristić:LB:76', 'Tapia:CDM:79', 'Dotor:CM:76', 'Cervi:CAM:77', 'Álvarez:RW:76', 'Douvikas:LW:78', 'Iglesias:ST:80', 'Paciência:ST:77'],
            'sev' => ['Nyland:GK:80', 'Carmona:RB:78', 'Badé:CB:81', 'Nianzou:CB:79', 'Pedrosa:LB:78', 'Gudelj:CDM:80', 'Agoumé:CM:78', 'Sow:CM:80', 'Lukebakio:RW:81', 'Ejuke:LW:80', 'Romero:ST:79', 'Fernández:GK:75', 'Navas:RB:80', 'Marcão:CB:78', 'Barco:LB:77', 'Lokonga:CDM:79', 'Saúl:CM:80', 'Suso:CAM:80', 'Idumbo:RW:75', 'Peque:LW:76', 'Iheanacho:ST:78', 'Kike:ST:76'],
            'mal' => ['Greif:GK:78', 'Maffeo:RB:80', 'Raíllo:CB:80', 'Valjent:CB:79', 'Mojica:LB:78', 'Costa:CDM:79', 'Darder:CM:81', 'Rodríguez:CM:80', 'Navarro:RW:77', 'Asano:LW:78', 'Muriqi:ST:81', 'Román:GK:74', 'Morey:RB:76', 'Copete:CB:77', 'Lato:LB:76', 'Mascarell:CDM:78', 'Morlanes:CM:77', 'Luna:CAM:75', 'Llabrés:RW:74', 'Radonjić:LW:77', 'Prats:ST:78', 'Larin:ST:78'],
            'ray' => ['Cárdenas:GK:78', 'Rațiu:RB:78', 'Mumin:CB:78', 'Lejeune:CB:80', 'Espino:LB:78', 'Valentín:CDM:80', 'López:CM:79', 'Trejo:CM:78', 'Palazón:RW:80', 'García:LW:81', 'Camello:ST:79', 'Batalla:GK:76', 'Balliu:RB:77', 'Aridane:CB:77', 'Chavarría:LB:76', 'Ciss:CDM:78', 'Pathé:CM:77', 'Nteka:CAM:76', 'De Frutos:RW:78', 'Embarba:LW:77', 'Trejo:ST:78', 'De Tomás:ST:79'],
            'ala' => ['Sivera:GK:80', 'Tenaglia:RB:78', 'Abqar:CB:78', 'Sedlar:CB:77', 'Sánchez:LB:77', 'Blanco:CDM:78', 'Guevara:CM:79', 'Guridi:CM:78', 'Vicente:RW:79', 'Conechny:LW:76', 'García:ST:79', 'Owono:GK:74', 'Novoa:RB:75', 'Mouriño:CB:76', 'Duarte:LB:77', 'Benavídez:CDM:77', 'Hagi:CM:76', 'Rebbach:CAM:75', 'Romero:RW:76', 'Rioja:LW:78', 'Villalibre:ST:77', 'Simeone:ST:76'],
            'pal' => ['Cillessen:GK:80', 'Rozada:RB:77', 'Suárez:CB:78', 'Mármol:CB:79', 'Muñoz:LB:77', 'Rodríguez:CDM:80', 'Campaña:CM:79', 'Moleiro:CM:81', 'Sandro:RW:78', 'Fuster:LW:77', 'McBurnie:ST:79', 'Horkaš:GK:74', 'Sinkgraven:RB:75', 'Curbelo:CB:76', 'Herzog:LB:75', 'Loiodice:CDM:78', 'González:CM:76', 'Perrone:CAM:78', 'Pejiño:RW:77', 'Marc:LW:76', 'Ramírez:ST:77', 'Mata:ST:77'],
            'leg' => ['Soriano:GK:78', 'Rosier:RB:78', 'Sergio:CB:77', 'Sáenz:CB:77', 'Hernández:LB:77', 'Tapia:CDM:79', 'Cissé:CM:76', 'Brašanac:CM:77', 'Cruz:RW:78', 'García:LW:78', 'Haller:ST:80', 'Dmitrović:GK:77', 'Altimira:RB:75', 'Porozo:CB:76', 'Franquesa:LB:76', 'Neyou:CDM:77', 'Chicco:CM:75', 'López:CAM:76', 'Munir:RW:78', 'Dani:LW:76', 'De la Fuente:ST:77', 'Gómez:ST:75'],
            'val2' => ['Hein:GK:78', 'Pérez:RB:77', 'Cömert:CB:78', 'Boyomo:CB:77', 'Rosa:LB:76', 'Jurić:CDM:77', 'Pérez:CM:78', 'Amallah:CM:78', 'Moro:RW:79', 'Ndiaye:LW:77', 'Latasa:ST:77', 'Ferreira:GK:74', 'Sánchez:RB:75', 'Sánchez:CB:76', 'Pérez:LB:75', 'Meseguer:CDM:76', 'Pérez:CM:75', 'Tuhami:CAM:76', 'Sylla:RW:77', 'Amath:LW:76', 'Machís:ST:77', 'Marcos:ST:76'],
            'esp' => ['García:GK:79', 'El Hilali:RB:77', 'Kumbulla:CB:78', 'Cabrera:CB:79', 'Romero:LB:78', 'Král:CDM:79', 'Gragera:CM:78', 'Lozano:CM:77', 'Tejero:RW:77', 'Puado:LW:80', 'Véliz:ST:78', 'Pacheco:GK:77', 'Gómez:RB:76', 'Calero:CB:77', 'Oliván:LB:77', 'Aguado:CDM:78', 'Barei:CM:75', 'Milla:CAM:78', 'Svensson:RW:74', 'Roca:LW:76', 'Cardona:ST:77', 'Cheddira:ST:77'],

            // EUROPEAN GIANTS
            'mci' => ['Ederson:GK:89', 'Walker:RB:85', 'Dias:CB:89', 'Akanji:CB:85', 'Gvardiol:LB:86', 'Rodri:CDM:92', 'Kovacic:CM:84', 'De Bruyne:CM:91', 'Silva:RW:88', 'Doku:LW:84', 'Haaland:ST:93', 'Ortega:GK:81', 'Lewis:RB:80', 'Stones:CB:86', 'Ake:LB:83', 'Nunes:CDM:81', 'Gundogan:CM:86', 'Foden:CAM:89', 'Savinho:RW:82', 'Grealish:LW:84', 'Bobb:ST:78', 'McAtee:ST:75'],
            'liv' => ['Alisson:GK:89', 'Alexander-Arnold:RB:87', 'Van Dijk:CB:89', 'Konate:CB:85', 'Robertson:LB:86', 'Endo:CDM:82', 'Mac Allister:CM:86', 'Szoboszlai:CM:84', 'Salah:RW:90', 'Diaz:LW:85', 'Jota:ST:85', 'Kelleher:GK:80', 'Bradley:RB:80', 'Quansah:CB:79', 'Tsimikas:LB:80', 'Gravenberch:CDM:84', 'Jones:CM:81', 'Elliott:CAM:81', 'Chiesa:RW:83', 'Gakpo:LW:83', 'Nunez:ST:84', 'Danns:ST:74'],
            'ars' => ['Raya:GK:86', 'White:RB:85', 'Saliba:CB:88', 'Gabriel:CB:86', 'Timber:LB:83', 'Partey:CDM:84', 'Rice:CM:88', 'Odegaard:CM:88', 'Saka:RW:89', 'Martinelli:LW:84', 'Havertz:ST:85', 'Neto:GK:81', 'Tomiyasu:RB:81', 'Kiwior:CB:80', 'Zinchenko:LB:82', 'Jorginho:CDM:83', 'Merino:CM:83', 'Nwaneri:CAM:75', 'Sterling:RW:83', 'Trossard:LW:84', 'Jesus:ST:84', 'Nketiah:ST:79'],
            'avl' => ['Martinez:GK:86', 'Cash:RB:81', 'Konsa:CB:82', 'Torres:CB:83', 'Digne:LB:80', 'Onana:CDM:82', 'Tielemans:CM:82', 'McGinn:CM:83', 'Bailey:RW:82', 'Rogers:LW:80', 'Watkins:ST:85', 'Olsen:GK:76', 'Bogarde:RB:75', 'Carlos:CB:80', 'Maatsen:LB:80', 'Kamara:CDM:82', 'Barkley:CM:79', 'Buendia:CAM:80', 'Philogene:RW:78', 'Iling-Jr:LW:77', 'Duran:ST:80', 'Young:ST:75'],
            'bay' => ['Neuer:GK:88', 'Boey:RB:81', 'Upamecano:CB:84', 'Kim:CB:85', 'Davies:LB:85', 'Palhinha:CDM:86', 'Kimmich:CM:87', 'Musiala:CM:89', 'Olise:RW:84', 'Gnabry:LW:84', 'Kane:ST:92', 'Ulreich:GK:77', 'Stanisic:RB:81', 'Dier:CB:81', 'Guerreiro:LB:83', 'Pavlovic:CDM:82', 'Laimer:CM:83', 'Muller:CAM:85', 'Sane:RW:85', 'Coman:LW:84', 'Tel:ST:80', 'Ibrahimovic:ST:75'],
            'dor' => ['Kobel:GK:86', 'Ryerson:RB:81', 'Anton:CB:82', 'Schlotterbeck:CB:84', 'Bensebaini:LB:80', 'Can:CDM:82', 'Gross:CM:81', 'Brandt:CM:84', 'Sabitzer:RW:82', 'Gittens:LW:80', 'Guirassy:ST:84', 'Meyer:GK:76', 'Couto:RB:80', 'Sule:CB:82', 'Kabar:LB:74', 'Nmecha:CDM:80', 'Reyna:CM:78', 'Wätjen:CAM:75', 'Adeyemi:RW:81', 'Malen:LW:82', 'Beier:ST:80', 'Haller:ST:79'],
            'rbl' => ['Gulacsi:GK:82', 'Geertruida:RB:81', 'Orban:CB:83', 'Lukeba:CB:82', 'Raum:LB:82', 'Haidara:CDM:81', 'Seiwald:CM:79', 'Simons:CM:85', 'Nusa:RW:79', 'Openda:LW:84', 'Sesko:ST:82', 'Vandevoordt:GK:76', 'Henrichs:RB:81', 'Bitshiabu:CB:76', 'Elmas:LB:79', 'Vermeeren:CDM:78', 'Kampl:CM:80', 'Baumgartner:CAM:80', 'Poulsen:RW:78', 'Silva:LW:78', 'Ouedraogo:ST:74', 'Gebel:ST:72'],
            'lev' => ['Hradecky:GK:83', 'Frimpong:RB:85', 'Tah:CB:85', 'Tapsoba:CB:84', 'Grimaldo:LB:86', 'Xhaka:CDM:86', 'Andrich:CM:83', 'Wirtz:CM:89', 'Hofmann:RW:83', 'Adli:LW:81', 'Boniface:ST:84', 'Kovar:GK:77', 'Arthur:RB:76', 'Hincapie:CB:83', 'Belocian:LB:76', 'Palacios:CDM:83', 'Garcia:CM:81', 'Tella:CAM:79', 'Schick:RW:82', 'Terrier:LW:81', 'Deli:ST:74', 'Puerta:ST:75'],
            'stu' => ['Nubel:GK:81', 'Vagnoman:RB:79', 'Rouault:CB:79', 'Chabot:CB:80', 'Mittelstadt:LB:81', 'Karazor:CDM:80', 'Stiller:CM:81', 'Millot:CM:80', 'Leweling:RW:79', 'Fuhrich:LW:81', 'Undav:ST:83', 'Bredlow:GK:75', 'Stenzel:RB:76', 'Zagadou:CB:79', 'Hendriks:LB:75', 'Keitel:CDM:76', 'Rieder:CM:78', 'Faghir:CAM:75', 'Raimund:RW:74', 'Demirovic:LW:80', 'Toure:ST:79', 'Diehl:ST:74'],
            'int' => ['Sommer:GK:85', 'Pavard:RB:84', 'Acerbi:CB:84', 'Bastoni:CB:86', 'Dimarco:LB:85', 'Calhanoglu:CDM:86', 'Barella:CM:87', 'Mkhitaryan:CM:83', 'Thuram:RW:85', 'Martinez:LW:88', 'Taremi:ST:83', 'Martinez:GK:76', 'Darmian:RB:81', 'Bisseck:CB:79', 'Augusto:LB:80', 'Asllani:CDM:78', 'Frattesi:CM:82', 'Zielinski:CAM:83', 'Dumfries:RW:82', 'Buchanan:LW:78', 'Arnautovic:ST:79', 'Correa:ST:78'],
            'mil' => ['Maignan:GK:87', 'Calabria:RB:81', 'Tomori:CB:84', 'Thiaw:CB:80', 'Hernandez:LB:86', 'Fofana:CDM:82', 'Reijnders:CM:82', 'Pulisic:CM:84', 'Chukwueze:RW:81', 'Leao:LW:86', 'Morata:ST:83', 'Sportiello:GK:77', 'Emerson:RB:80', 'Pavlovic:CB:80', 'Terracciano:LB:75', 'Bennacer:CDM:82', 'Loftus-Cheek:CM:81', 'Musah:CAM:79', 'Okafor:RW:80', 'Saelemaekers:LW:79', 'Abraham:ST:81', 'Jovic:ST:79'],
            'juv' => ['Di Gregorio:GK:82', 'Cambiaso:RB:82', 'Bremer:CB:86', 'Gatti:CB:81', 'Cabal:LB:79', 'Locatelli:CDM:82', 'Luiz:CM:83', 'Koopmeiners:CM:85', 'Gonzalez:RW:82', 'Yildiz:LW:81', 'Vlahovic:ST:85', 'Perin:GK:79', 'Kalulu:RB:80', 'Danilo:CB:82', 'Savona:LB:76', 'Fagioli:CDM:80', 'Thuram:CM:81', 'McKennie:CAM:80', 'Weah:RW:79', 'Conceicao:LW:81', 'Milik:ST:80', 'Mbangula:ST:75'],
            'ata' => ['Carnesecchi:GK:81', 'Bellanova:RB:81', 'Hien:CB:80', 'Djimsiti:CB:80', 'Ruggeri:LB:80', 'De Roon:CDM:81', 'Ederson:CM:83', 'Pasalic:CM:81', 'De Ketelaere:RW:82', 'Lookman:LW:84', 'Retegui:ST:82', 'Patricio:GK:79', 'Kossounou:RB:80', 'Toloi:CB:79', 'Zappacosta:LB:80', 'Sulemana:CDM:76', 'Samardzic:CM:80', 'Brescianini:CAM:78', 'Zaniolo:RW:79', 'Cuadrado:LW:78', 'Scamacca:ST:82', 'Gasperini:ST:70'],
            'bol' => ['Skorupski:GK:80', 'Posch:RB:80', 'Beukema:CB:79', 'Lucumi:CB:80', 'Miranda:LB:78', 'Freuler:CDM:80', 'Aebischer:CM:79', 'Fabbian:CM:78', 'Orsolini:RW:81', 'Ndoye:LW:79', 'Castro:ST:79', 'Ravaglia:GK:74', 'Holm:RB:77', 'Casale:CB:78', 'Lykogiannis:LB:76', 'Moro:CDM:77', 'Pobega:CM:77', 'Urbanski:CAM:75', 'Karlsson:RW:78', 'Iling-Junior:LW:77', 'Dallinga:ST:78', 'Odgaard:ST:77'],
            'psg' => ['Donnarumma:GK:88', 'Hakimi:RB:86', 'Marquinhos:CB:87', 'Pacho:CB:82', 'Mendes:LB:85', 'Neves:CDM:84', 'Vitinha:CM:86', 'Zaire-Emery:CM:83', 'Dembele:RW:86', 'Barcola:LW:85', 'Ramos:ST:84', 'Safonov:GK:80', 'Zague:RB:75', 'Skriniar:CB:84', 'Beraldo:LB:80', 'Fabian:CDM:83', 'Ruiz:CM:83', 'Doue:CAM:80', 'Lee:RW:81', 'Asensio:LW:83', 'Kolo Muani:ST:83', 'Mbaye:ST:75'],
            'mon' => ['Kohn:GK:78', 'Singo:RB:80', 'Kehrer:CB:80', 'Salisu:CB:79', 'Jakobs:LB:78', 'Zakaria:CDM:81', 'Camara:CM:80', 'Golovin:CM:82', 'Akliouche:RW:79', 'Ben Seghir:LW:78', 'Embolo:ST:80', 'Majecki:GK:76', 'Teze:RB:77', 'Mawissa:CB:75', 'Ouattara:LB:76', 'Matazo:CDM:76', 'Magassa:CM:77', 'Minamino:CAM:80', 'Diatta:RW:78', 'Balogun:LW:79', 'Ilenikhena:ST:76', 'Michelin:ST:74'],
            'bre' => ['Bizot:GK:79', 'Lala:RB:78', 'Chardonnet:CB:79', 'Coulibaly:CB:77', 'Amavi:LB:76', 'Lees-Melou:CDM:80', 'Magnetti:CM:77', 'Camara:CM:78', 'Del Castillo:RW:80', 'Faivre:LW:78', 'Ajorque:ST:78', 'Coudert:GK:73', 'Zogbe:RB:74', 'Ndiaye:CB:76', 'Haidara:LB:76', 'Martin:CDM:77', 'Doumbia:CM:77', 'Pereira:CAM:76', 'Sima:RW:77', 'Salah:LW:75', 'Baldé:ST:76', 'Camblan:ST:74'],
            'lil' => ['Chevalier:GK:82', 'Meunier:RB:78', 'Diakite:CB:80', 'Alexsandro:CB:79', 'Gudmundsson:LB:78', 'Andre:CDM:81', 'Gomes:CM:81', 'Cabella:CM:79', 'Zhegrova:RW:82', 'Sahraoui:LW:78', 'David:ST:84', 'Mannone:GK:74', 'Tiago:RB:77', 'Umtiti:CB:78', 'Ismaily:LB:78', 'Bouaddi:CDM:75', 'Mukau:CM:75', 'Fernandez:CAM:76', 'Bakker:RW:76', 'Ilic:LW:75', 'Bayo:ST:77', 'Mbappe:ST:74'],
            'psv' => ['Benitez:GK:80', 'Karsdorp:RB:79', 'Flamingo:CB:77', 'Boscagli:CB:80', 'Dams:LB:76', 'Schouten:CDM:81', 'Veerman:CM:82', 'Tillman:CM:80', 'Bakayoko:RW:82', 'Lang:LW:80', 'De Jong:ST:82', 'Drommel:GK:74', 'Oppegard:RB:75', 'Nagalo:CB:76', 'Obispo:LB:77', 'Saibari:CDM:79', 'Lozano:CM:80', 'Babadi:CAM:76', 'Pepi:RW:78', 'Driouech:LW:76', 'Land:ST:74', 'Bresser:ST:73'],
            'fey' => ['Wellenreuther:GK:78', 'Lotomba:RB:77', 'Beelen:CB:78', 'Hancko:CB:82', 'Bueno:LB:78', 'Timber:CDM:81', 'Hwang:CM:79', 'Milambo:CM:78', 'Paixao:RW:80', 'Ivanusec:LW:79', 'Gimenez:ST:82', 'Bijlow:GK:79', 'Read:RB:74', 'Trauner:CB:79', 'Smal:LB:77', 'Zerrouki:CDM:78', 'Zechiël:CM:75', 'Stengs:CAM:80', 'Nadje:RW:76', 'Osman:LW:77', 'Carranza:ST:76', 'Ueda:ST:77'],
            'spo' => ['Israel:GK:78', 'Debast:RB:79', 'Diomande:CB:82', 'Inacio:CB:83', 'Santos:LB:79', 'Hjulmand:CDM:82', 'Morita:CM:80', 'Braganca:CM:79', 'Trincao:RW:82', 'Pote:LW:83', 'Gyokeres:ST:86', 'Kovacevic:GK:77', 'Fresneda:RB:77', 'Reis:CB:78', 'Quaresma:LB:77', 'Essugo:CDM:76', 'Edwards:CM:80', 'Harder:CAM:77', 'Araujo:RW:76', 'Quenda:LW:78', 'Ribeiro:ST:75', 'Nel:ST:74'],
            'ben' => ['Trubin:GK:81', 'Bah:RB:80', 'Silva:CB:83', 'Otamendi:CB:81', 'Carreras:LB:79', 'Florentino:CDM:81', 'Aursnes:CM:81', 'Kokcu:CM:82', 'Di Maria:RW:83', 'Akturkoglu:LW:81', 'Pavlidis:ST:81', 'Gomes:GK:75', 'Kabore:RB:78', 'Araujo:CB:79', 'Beste:LB:78', 'Barreiro:CDM:79', 'Rollheiser:CM:78', 'Sanches:CAM:79', 'Amoura:RW:79', 'Schjelderup:LW:77', 'Cabral:ST:79', 'Prestianni:ST:76'],
            'bru' => ['Mignolet:GK:78', 'Seys:RB:75', 'Mechele:CB:77', 'Ordonez:CB:76', 'De Cuyper:LB:78', 'Onyedika:CDM:78', 'Jashari:CM:76', 'Vanaken:CM:80', 'Skov Olsen:RW:80', 'Tzolis:LW:78', 'Nilsson:ST:77', 'Jackers:GK:72', 'Sabbe:RB:74', 'Spileers:CB:75', 'Romero:LB:74', 'Vetlesen:CDM:77', 'Nielsen:CM:76', 'Talbi:CAM:75', 'Skoras:RW:76', 'Jutgla:LW:77', 'Vermant:ST:74', 'Zinckernagel:ST:76'],
            'cel_sco' => ['Schmeichel:GK:78', 'Johnston:RB:78', 'Carter-Vickers:CB:78', 'Scales:CB:76', 'Taylor:LB:76', 'McGregor:CDM:79', 'Hatate:CM:78', 'Engels:CM:77', 'Kuhn:RW:77', 'Maeda:LW:77', 'Kyogo:ST:79', 'Sinisalo:GK:73', 'Ralston:RB:74', 'Trusty:CB:75', 'Valle:LB:75', 'Bernardo:CDM:76', 'McCarthy:CM:74', 'Forrest:CAM:75', 'Palma:RW:76', 'Yang:LW:74', 'Idah:ST:75', 'Turley:ST:70'],
            'sha' => ['Riznyk:GK:76', 'Konoplia:RB:76', 'Matviyenko:CB:79', 'Bondar:CB:77', 'Azarovi:LB:76', 'Stepanenko:CDM:78', 'Sudakov:CM:80', 'Kryskiv:CM:77', 'Zubkov:RW:78', 'Kevin:LW:76', 'Sikan:ST:77', 'Fesyun:GK:72', 'Tobias:RB:75', 'Franjic:CB:75', 'Gocholeishvili:LB:75', 'Bondarenko:CDM:77', 'Marlon:CM:76', 'Pedrinho:CAM:76', 'Eguinaldo:RW:75', 'Gomes:LW:74', 'Traore:ST:76', 'Newertton:ST:73'],
            'sal' => ['Blaswich:GK:77', 'Dedic:RB:78', 'Piatkowski:CB:76', 'Baidoo:CB:75', 'Terzic:LB:76', 'Gourna-Douath:CDM:77', 'Kjaergaard:CM:76', 'Gloukh:CM:79', 'Nene:RW:76', 'Daghim:LW:75', 'Konate:ST:77', 'Schlager:GK:75', 'Morgalla:RB:74', 'Blank:CB:74', 'Guindo:LB:74', 'Diambou:CDM:74', 'Capaldo:CM:76', 'Bidstrup:CAM:75', 'Clark:RW:75', 'Ratkov:LW:75', 'Fernando:ST:76', 'Yeo:ST:73'],
            'you' => ['Von Ballmoos:GK:76', 'Athekame:RB:74', 'Camara:CB:76', 'Zoukrou:CB:74', 'Hadjjam:LB:74', 'Lauper:CDM:75', 'Ugrinic:CM:77', 'Imeri:CM:75', 'Monteiro:RW:76', 'Colley:LW:75', 'Ganvoula:ST:75', 'Keller:GK:72', 'Blum:RB:74', 'Crnovrsanin:CB:73', 'Conté:LB:73', 'Niasse:CDM:75', 'Chaiwa:CM:72', 'Males:CAM:74', 'Elia:RW:76', 'Itten:LW:75', 'Virginius:ST:74', 'Lakomy:ST:73'],
            'zag' => ['Nevistic:GK:75', 'Ristovski:RB:76', 'Bernauer:CB:75', 'Theophile-Catherine:CB:76', 'Pierre-Gabriel:LB:75', 'Misic:CDM:77', 'Sucic:CM:76', 'Baturina:CM:79', 'Cordoba:RW:75', 'Pjaca:LW:76', 'Petkovic:ST:78', 'Zagorac:GK:72', 'Mmaee:RB:74', 'Torrente:CB:74', 'Ogiwara:LB:74', 'Ademi:CDM:76', 'Kacavenda:CM:74', 'Rog:CAM:75', 'Spikic:RW:75', 'Stojkovic:LW:74', 'Kulenovic:ST:76', 'Hoxha:ST:74'],
            'crv' => ['Glazer:GK:76', 'Seol:RB:75', 'Spajic:CB:76', 'Djiga:CB:75', 'Rodic:LB:75', 'Elšnik:CDM:76', 'Krunic:CM:78', 'Ilić:CM:75', 'Mvumpa:RW:76', 'Olayinka:LW:76', 'Ndiaye:ST:77', 'Ilić:GK:72', 'Mimovic:RB:73', 'Drkusic:CB:75', 'Lekovic:LB:73', 'Ivanic:CDM:77', 'Hwang:CM:76', 'Milson:CAM:75', 'Maksimovic:RW:74', 'Katai:LW:75', 'Duarte:ST:76', 'Sremcevic:ST:72'],
            'spa' => ['Vindahl:GK:75', 'Wiesner:RB:75', 'Vitik:CB:77', 'Panak:CB:76', 'Zeleny:LB:75', 'Kairinen:CDM:76', 'Laci:CM:76', 'Preciado:CM:77', 'Birmancevic:RW:78', 'Haraslin:LW:78', 'Olatunji:ST:76', 'Jensen:GK:72', 'Mejdr:RB:73', 'Ross:CB:74', 'Suchomel:LB:73', 'Pavelka:CDM:74', 'Sadilek:CM:76', 'Danek:CAM:74', 'Krasniqi:RW:75', 'Rrahmani:LW:76', 'Tuci:ST:74', 'Kuchta:ST:76'],
            'fer' => ['Dibusz:GK:76', 'Makreckis:RB:74', 'Cisse:CB:75', 'Gustavo:CB:74', 'Ramirez:LB:74', 'Rommens:CDM:74', 'Maiga:CM:74', 'Abu Fani:CM:76', 'Zachariassen:RW:75', 'Traore:LW:76', 'Varga:ST:77', 'Varga:GK:71', 'Toth:RB:72', 'Szabo:CB:72', 'Botka:LB:73', 'Papp:CDM:72', 'Besic:CM:74', 'Toth:CAM:72', 'Kady:RW:75', 'Kehinde:LW:74', 'Pesic:ST:75', 'Saldanha:ST:76'],
            'stg' => ['Scherpen:GK:74', 'Gazibegovic:RB:75', 'Aiwu:CB:74', 'Lavalée:CB:73', 'Johnston:LB:74', 'Stankovic:CDM:75', 'Horvat:CM:75', 'Kiteishvili:CM:76', 'Bøving:RW:74', 'Jatta:LW:74', 'Biereth:ST:75', 'Khudyakov:GK:71', 'Geyrhofer:RB:72', 'Malić:CB:72', 'Schnegg:LB:73', 'Chukwuani:CDM:73', 'Zvonarek:CM:73', 'Camara:CAM:72', 'Yardımcı:RW:73', 'Grgić:LW:72', 'Sarkaria:ST:74', 'Wlodarczyk:ST:73'],
        ];

        foreach ($teams as $team) {
            $initialStats = json_encode(['played' => 0, 'won' => 0, 'drawn' => 0, 'lost' => 0, 'gf' => 0, 'ga' => 0, 'gd' => 0, 'points' => 0, 'form' => []]);
            $uclStats = $team['isUCL'] ? json_encode(['played' => 0, 'won' => 0, 'drawn' => 0, 'lost' => 0, 'gf' => 0, 'ga' => 0, 'gd' => 0, 'points' => 0, 'rank' => 0]) : null;

            DB::table('teams')->insert(array_merge($team, ['stats' => $initialStats, 'uclStats' => $uclStats, 'created_at' => $now, 'updated_at' => $now]));

            if (isset($realPlayers[$team['id']])) {
                // Completely hardcoded and precise 1-11 Starting line, exactly 11 players on bench.
                foreach ($realPlayers[$team['id']] as $idx => $pString) {
                    $parts = explode(':', $pString);
                    DB::table('players')->insert([
                        'id' => Str::uuid(),
                        'team_id' => $team['id'],
                        'name' => $parts[0],
                        'number' => $idx + 1,
                        'position' => $parts[1] ?? 'RES',
                        'rating' => isset($parts[2]) ? (int)$parts[2] : 75,
                        'offField' => $idx >= 11, // First 11 are meticulously ordered exactly as 4-3-3 shape
                        'created_at' => $now,
                        'updated_at' => $now
                    ]);
                }
            }
        }
    }
}